%%{init: {"flowchart":{"htmlLabels":true}} }%%
graph LR
  A["<a href='javascript:window.MM6=1'>CANARY-MM6</a>"]
  B["<iframe srcdoc='&lt;script&gt;parent.MM7=1&lt;/script&gt;'></iframe>CANARY-MM7"]
  C["<svg onload='window.MM8=1'></svg>CANARY-MM8"]
