graph TD
  A[CANARY-MM9] --> B
  click A href "javascript:window.MM10=1" _self
  A2["<foreignObject><body xmlns='http://www.w3.org/1999/xhtml'><img src=x onerror='window.MM11=1'></body></foreignObject>CANARY-MM11"]
